name: "Deploy site and functions"
on:
  push:
    branches:
      - main

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities-and-aws
  cancel-in-progress: true

jobs:
  deploy:
    name: "Deploy site and functions"
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
      - run: npm install
      - run: npm run build

      - run: cp -r data functions/log-view
      - run: npm run build-function
      - uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEOCITIES_TOKEN }}
          dist_dir: "dist/"
          cleanup: true # delete anything on neocities that's not in my dist_dir

      - name: Zip Lambda function
        run: |
          cd functions/log-view/dist
          zip -r function.zip bundle.js

      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name LFZ-logview --zip-file fileb://functions/log-view/dist/function.zip

